{% set name = "mir_eval" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mir_eval-{{ version }}.tar.gz
  sha256: e1febaa5766c65a7545c2a170b241490f47a98987370b1e06742424c5debe65e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.7.0, <1.24.0
    - scipy >=1.0.0
    - future
    - six

test:
  imports:
    - mir_eval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/craffel/mir_eval
  summary: Common metrics for common audio/music processing tasks.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bmcfee
